version: '2'
services:
    projet-app:
        image: projet
        external_links:
            - projet-mysql:mysql
            - projet-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/projet?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    projet-mysql:
        extends:
            file: mysql.yml
            service: projet-mysql
    projet-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: projet-elasticsearch
